import React from 'react'
import Link from 'next/link'

export const metadata = {
    title: "About Layouts",
    description: "Generated by create next app",
};

function AboutLayout({ children }) {
    return (
        <div className='p-2'>
            <nav>
                <ul className="flex flex-row gap-6">
                    Our Blogs

                </ul>
            </nav>

            {children}
        </div>
    )
}

export default AboutLayout
