import Link from 'next/link'
import React from 'react'

export const metadata = {
    title: "Bloks Layout",
    description: "Generated by create next app",
  };

function Blogs() {
    const blogs = [{
        id: 1,
        title: 'Blog 1',
        descriptins: "blog 1 description"
    },
    {
        id: 2,
        title: 'Blog 2',
        descriptins: "blog 2 description"
    },
    {
        id: 3,
        title: 'Blog 3',
        descriptins: "blog 3 description"
    }]
    return (
        <main>
            <ul>
                {blogs.map((blog)=>(
                    <li className='p-4' key={blog.id} blog={blog}><Link href={`/blogs/${blog.id}`}>{blog.title}</Link></li>
                ))}
            </ul>
        </main>
    )
}

export default Blogs
